// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IBiCaretDown: typeof import('~icons/bi/caret-down')['default']
    IBiDownload: typeof import('~icons/bi/download')['default']
    IBiGithub: typeof import('~icons/bi/github')['default']
    IBiLinkedin: typeof import('~icons/bi/linkedin')['default']
    ILogosFirebase: typeof import('~icons/logos/firebase')['default']
    ILogosFlask: typeof import('~icons/logos/flask')['default']
    ILogosGoogleCloud: typeof import('~icons/logos/google-cloud')['default']
    ILogosNextjsIcon: typeof import('~icons/logos/nextjs-icon')['default']
    ILogosPython: typeof import('~icons/logos/python')['default']
    ILogosReact: typeof import('~icons/logos/react')['default']
    ILogosSvelteIcon: typeof import('~icons/logos/svelte-icon')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
