// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IBiCaretDown: typeof import('~icons/bi/caret-down')['default']
    IBiDownload: typeof import('~icons/bi/download')['default']
    IBiGithub: typeof import('~icons/bi/github')['default']
    IBiLinkedin: typeof import('~icons/bi/linkedin')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
